// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXwbtrJkYw1sEXbJWjwC6Cgh4pprizT9k',
    appId: '1:551110643156:web:6897fac5e1766eccb51a41',
    messagingSenderId: '551110643156',
    projectId: 'colae-app',
    authDomain: 'colae-app.firebaseapp.com',
    storageBucket: 'colae-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmZdg6iL9BsrPRadhTDFRB9GrYResV-s',
    appId: '1:551110643156:android:645ec748c715ae0eb51a41',
    messagingSenderId: '551110643156',
    projectId: 'colae-app',
    storageBucket: 'colae-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnLd3i4PbeiejsR1txMIZfxEvE-9cRUhY',
    appId: '1:551110643156:ios:9306775b54129e84b51a41',
    messagingSenderId: '551110643156',
    projectId: 'colae-app',
    storageBucket: 'colae-app.firebasestorage.app',
    iosBundleId: 'com.dev.colaeCut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnLd3i4PbeiejsR1txMIZfxEvE-9cRUhY',
    appId: '1:551110643156:ios:9306775b54129e84b51a41',
    messagingSenderId: '551110643156',
    projectId: 'colae-app',
    storageBucket: 'colae-app.firebasestorage.app',
    iosBundleId: 'com.dev.colaeCut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXwbtrJkYw1sEXbJWjwC6Cgh4pprizT9k',
    appId: '1:551110643156:web:42fec06911539a1fb51a41',
    messagingSenderId: '551110643156',
    projectId: 'colae-app',
    authDomain: 'colae-app.firebaseapp.com',
    storageBucket: 'colae-app.firebasestorage.app',
  );
}
